### ISSUE TITLE
Question: Writing backtest results as they are received

### ISSUE THREAD

**Issue by kjanoudi** [timelyart/Kairos#10]
It looks like right now, backtest results are stored in some place in memory, then written to a file after the successful completion of all the tests. Would it be difficult to write to a log file with the results of the backtest as it runs?

**Comment by timelyart** [comment]
It is not simple to change because of how it calculates aggregates and averages. It can be changed but it requires a different way of going about it - possibly introducing a database like SQLite to store the raw results.
