### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by oimista** [timelyart/Kairos#101]
Sorry I didn't get back to the other thread, had a vacation and forgot to update the thread. I got it working using your suggestion.

I've got a new issue now where I have a captcha preventing the app from loging in, is there anyway around that?

I can't find anything in TV to disable or allow ignore requests from certain devices/IP's.

Thanks

**Comment by timelyart** [comment]
> Sorry I didn't get back to the other thread, had a vacation and forgot to update the thread. I got it working using your suggestion.

No problem. Happy to hear you got it working.
> I've got a new issue now where I have a captcha preventing the app from loging in, is there anyway around that?

I doubt there is. Things like Cloudflare will be hard to counter. I can maybe scan for the captcha, and ask for a manual login. It shouldn't happen often though.

**Comment by oimista** [comment]
Thanks for the reply, I didn't think there would be anyway around the captcha, have opened a ticket with TV support to see what they say.

**Comment by timelyart** [comment]
I doubt they will do anything about it but keep me posted, please.

**Comment by oimista** [comment]
I only got some generic answer from them, but I do now seem to be able to use the app again to create alerts.

I am having an issue with creating an alert with the second box being Any alert() function call and get an error:

Traceback (most recent call last):
  File "C:\Kairos-3.1\tv\tv.py", line 2447, in create_alert
    wait_and_click(browser, 'button[data-name="once-per-bar-close"]')
  File "C:\Kairos-3.1\tv\tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium-4.8.2-py3.11.egg\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException:

<img width="346" alt="any-alert" src="https://user-images.githubusercontent.com/123581127/226111155-813218c0-5800-40f5-ae37-5dbb04f92434.png">

**Comment by timelyart** [comment]
Please, create a separate issue for your new problem.  Otherwise, this repo will become a mess quite quickly. 

Closing this one as it is beyond the scope of what Kairos can and should do.
