### ISSUE TITLE
export.yaml fails

### ISSUE THREAD

**Issue by enyan0** [timelyart/Kairos#102]
Something must have changed, as export.yaml fails catching an error on:

 \tv.py", line 1512, in open_chart
    set_timeframe(browser, timeframe)
 \tv.py", line 547, in set_timeframe
    wait_and_click(browser, css_selectors['btn_timeframe'])
 \tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Increasing delays in kairos.cfg does not fix the issue. It only moves the error to:

 \tv.py", line 1667, in change_symbol
    wait_and_click(browser, css_selectors['btn_input_symbol'])
\tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(

**Comment by timelyart** [comment]
Confirmed. TV has made changes to the CSS. Working on fixing it now.

**Comment by timelyart** [comment]
Fixed in [release v3.3](https://github.com/timelyart/Kairos/releases/tag/v3.3).
