### ISSUE TITLE
Can not turn to Conditions on Tradingview

### ISSUE THREAD

**Issue by ducky1022** [timelyart/Kairos#105]
![image](https://user-images.githubusercontent.com/130341589/231617975-597d24a5-2cba-4430-943e-23d44e9b58d5.png)
Traceback (most recent call last):
  File "c:\Kairos-master\tv\tv.py", line 2376, in create_alert
    wait_and_click(alert_dialog, css_1st_row_left, 30)
  File "c:\Kairos-master\tv\tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(
  File "C:\Users\Ducky\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium-4.8.3-py3.10.egg\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00C1DCE3+50899]
        (No symbol) [0x00BAE111]
        (No symbol) [0x00AB5588]
        (No symbol) [0x00AE08F9]
        (No symbol) [0x00AE0AFB]
        (No symbol) [0x00AD8F71]
        (No symbol) [0x00AFB944]
        (No symbol) [0x00AD8EC6]
        (No symbol) [0x00AFBC54]
        (No symbol) [0x00B0E01C]
        (No symbol) [0x00AFB6F6]
        (No symbol) [0x00AD7708]
        (No symbol) [0x00AD886D]
        GetHandleVerifier [0x00E83EAE+2566302]
        GetHandleVerifier [0x00EB92B1+2784417]
        GetHandleVerifier [0x00EB327C+2759788]
        GetHandleVerifier [0x00CB5740+672048]
        (No symbol) [0x00BB8872]
        (No symbol) [0x00BB41C8]
        (No symbol) [0x00BB42AB]
        (No symbol) [0x00BA71B7]
        BaseThreadInitThunk [0x774200F9+25]
        RtlGetAppContainerNamedObjectPath [0x77E27BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77E27B8E+238]

Hi timelyart,
Could you please help me to figure out this problem? Kairos can not auto to choose the conditions and stuck in the step (image below)
Thanks

**Comment by timelyart** [comment]
Please share the YAML file you are using (remove any confidential data).
Also, what type of membership are you on?

**Comment by ducky1022** [comment]
[alert.txt](https://github.com/timelyart/Kairos/files/11221874/alert.txt)
Hi,
I am used _alert.yaml on Kairos-master. (please see the file is attached)
And i'm using Trading view with PRO membership.

Thank you for your help. 
Have a lovely day!

**Comment by timelyart** [comment]
CSS changed of menu items. Working on fixing it.

**Comment by timelyart** [comment]
Fixed in [v3.4](https://github.com/timelyart/Kairos/releases/tag/v3.4).
