### ISSUE TITLE
login and export

### ISSUE THREAD

**Issue by enyan0** [timelyart/Kairos#108]
Can't login anymore:

2023-05-22 07:43:05.969 INFO tv - accept_cookies: cookies already accepted
2023-05-22 07:43:36.144 ERROR tv - login: Message:

2023-05-22 07:43:36.857 ERROR tv - snapshot: log\20230522_074336.png

While session was still active I had ERROR open chart using export.yaml

**Comment by timelyart** [comment]
Can you share the print screen?

**Comment by timelyart** [comment]
I did find a problem with the export data dialog which is fixed in [release v3.8](https://github.com/timelyart/Kairos/releases/tag/v3.8).

**Comment by timelyart** [comment]
> Can you share the print screen?

Never mind. I could reproduce this issue as well and was fixed with [release v3.8](https://github.com/timelyart/Kairos/releases/tag/v3.8) as well.

Thank you for reporting these problems.

**Comment by enyan0** [comment]
thanks! all working in the new version.
