### ISSUE TITLE
run, chart, logout

### ISSUE THREAD

**Issue by enyan0** [timelyart/Kairos#109]
I also tried longer delays, just in case, but it seems broken. 

This is export.yaml: 
![1](https://github.com/timelyart/Kairos/assets/5871374/526367b1-b0da-4130-a2f6-fbbe6045f3dd)
![2](https://github.com/timelyart/Kairos/assets/5871374/ab1944d2-c471-4164-90f1-fab164700317)
![3](https://github.com/timelyart/Kairos/assets/5871374/245db462-f62f-40ca-b666-39dd87046742)
![4](https://github.com/timelyart/Kairos/assets/5871374/07bbbc83-a364-4530-aa4c-6c5a6b8cdf41)
![7](https://github.com/timelyart/Kairos/assets/5871374/3eb80eae-8821-4c37-8adc-a79b9ee892eb)

alerts.yaml:
![Screenshot (14)](https://github.com/timelyart/Kairos/assets/5871374/e9415cc7-3b6c-478c-8404-0269ac0d354e)

![Screenshot (15)](https://github.com/timelyart/Kairos/assets/5871374/abeefd78-fd22-4d22-9617-3cbccc8dd6fb)

I saw it also on import watchlist.

**Comment by timelyart** [comment]
Thank you for posting. I'll investigate.

**Comment by timelyart** [comment]
The domain model changed for the website. Fixing it now.

**Comment by timelyart** [comment]
Fixed with [release v3.9](https://github.com/timelyart/Kairos/releases/tag/v3.9).

**Comment by enyan0** [comment]
The problem has reappered unfortunately... I can confirm this for at least yaml export, alert and import watchlist.
Thank you for fixing these!
![Screenshot (16)](https://github.com/timelyart/Kairos/assets/5871374/8361b47c-1912-405f-923e-f615235552e1)

**Comment by timelyart** [comment]
Please try the following: 
* clear the browsing history/data first
* run `python main.py -cls`  (removes all copies of your browser user profile)
* run Kairos normally

This will make sure that Kairos isn't using old data (i.e. the old layout).
Let me know if that fixes it for you.

**Comment by enyan0** [comment]
v3.9 worked just fine for a day or so. Then it didn't.
This is testing on both old and new environments, also including fresh install of chrome, both linux and windows, and different machines. It gets stuck at login:
<img width="790" alt="Image 001" src="https://github.com/timelyart/Kairos/assets/5871374/7c317815-c2d5-4bc7-a9f9-90d73a507e5d">

**Comment by timelyart** [comment]
I cleared my browser, removed the old profiles (as per my own recommendation) and cleared the cache of pycharm. 
Unfortunately, it works fine for me. 

It may be a case of them not having updated the DOM on all servers. Admittedly, that would be strange but that is the only thing I can think of. For a week, I will test every day and let you know what my findings are.

**Comment by timelyart** [comment]
I ran into CAPTCHA issues today. Which may be what has been bothering you as well. 
I am working on a fix but it is quite complicated as I am trying to incorporate anti captcha extensions. 

In the mean time, you can try the following steps:
1. manually login (set the _remember me_  checkbox to **true**)
2. close the browser
3. run `python main.py -cls`
4. run Kairos normally

**Comment by enyan0** [comment]
Yes. It is the captcha for me too.

**Comment by mrcrdwd** [comment]
Same issue CAPTCHA issue over here. This is going to be an interesting one on a headless machine.

**Comment by timelyart** [comment]
Release [v3.10](https://github.com/timelyart/Kairos/releases/tag/v3.10) is an attempt in handling the reCAPTCHA. 

The preferred way to handle this is with the CAPTCHA handling extension called NoCAPTCHA which you will need to install. There may be others, but from what I encountered most have either a paywall or don't solve the challenge automatically (or both). NoCAPTCHA handles the first 100 challenges per 24 hours for free. I am open to test other extensions provided they work automatically, and without a paywall for the first 20 challenges per day.

In addition, you will need to set `captcha_extension = true` under the `[webdriver]` section in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/master/_kairos.cfg).

Although I did extensive testing, please let me know if this works for you by leaving a comment below.

**Comment by mrcrdwd** [comment]
Good work @timelyart. Testing it now but haven't come across the CAPTCHA yet. So far so good.

How would this work on truly headless service like a VPS for instance? 

~~I'm curious if CAPTCHA is limited to certain types of browsers. So for instance what if Kairos would identify itself in the user agent as a screen reader during login? Maybe that would prevent the CAPTCHA from appearing.~~ Nevermind, this won't work.

It's funny that extensions like NopeCHA exist. Has AI marked the end of reCAPTCHA? :)

**UPDATE**
I'm sure you've already come across https://pypi.org/project/selenium-stealth/ and https://github.com/thicccat688/selenium-recaptcha-solver ? The second one is especially interesting as it uses CAPTCHA audio, transcribes that and then prompts the answer. Speech-to-text these days is a piece of cake of course.

**Comment by timelyart** [comment]
Thank you. Funnily enough I haven't looked at libraries. I looked at APIs first, but from what I have seen they are all behind a paywall. 

Selenium Stealth seems a no brainer. Being able to set your user agent is a great feature to have. I will have a look at the recaptcha solver as well. If it works just as well, it would require no additional hoops from the end user. 

I have no idea how this would work on VPS - I no longer use such a service but maintain my own server (debian) on a different location. My server does have a GUI though. I am working on being able to make Kairos load the extension but that requires a *.cpx file, which you can easily made from within the (Chrome) browser, but likely will be a challenge on VPS.

And yes, I read somewhere that Google has given up on (re)CAPTCHA because of AI.

**Comment by timelyart** [comment]
@mrcrdwd which operating systems are you using again?

**Comment by mrcrdwd** [comment]
Yeah, I'd say Selenium Stealth would be a good thing to integrate, regardless of the captcha stuff. 

The recaptcha resolver is just a very smart way to get around this issue. It uses https://pypi.org/project/SpeechRecognition/ which in turn supports Whisper. I can imagine this would get close to 100% accuracy.

Would be interesting to see Kairos support loading extensions. Didn't know that was possible. But than again it doesn't surprise me :)

@timelyart I'm running both Ubuntu (headless) and OSX.

**Comment by enyan0** [comment]
The extension works fine on windows and I think it is a nice fall back option. If something there happens, I will report back.

On linux I cant confirm because of other issues that I am having there.
I am on ubuntu 22. I followed instructions except for python version. I tested python 3.9, 3.10, 3.11 and chromedriver which is the latest. 
On linux I cannot run it, Headless or not. While not headless, it could not get past this error, also when using kairos v3.9, or while on windows and not using conda:
![Screenshot 2023-07-06 170121](https://github.com/timelyart/Kairos/assets/5871374/470b37bc-b443-4ad7-87eb-7795150c46e2)


Worth noting is that if I run chromedriver with this only argument and replacing the else block, at line 3228, in tv.py, with:
browser = webdriver.Chrome(options=options)

it runs until the end but only because it does not load the chromedriver and nothing is actually done.
~~...it runs apparently fine processing all symbols until the end but chrome cannot render on screen at any point during the run, and, mostly important, no file is saved in the export folder specified in yaml. Folders are created, symbols are reportedly processed but chart files are not saved.~~

**Comment by mrcrdwd** [comment]
@enyan0 what happens if you just comment out the option `executable_path` in your `kairos.cfg`? I checked my config and I don't have that option in there.

**Comment by timelyart** [comment]
`executable_path` does nothing, `path`, `download_path` and `web_browser_path` are valid settings in *kairos.cfg*

`path` equates to _executable_path_ and should be the path to your webdriver.

**Comment by timelyart** [comment]
I also apologize for not being able to do much on Kairos the past week, I have been too busy with other stuff. Next week should be better.

**Comment by enyan0** [comment]
@mrcrdwd what version of ubuntu / python are you on? The fact that this same error appears on windows when not using conda makes me think that something may be up with the environment.

**Comment by timelyart** [comment]
Seems the argument `executable_path` was removed in Selenium 4.10. 

Apparently, as of Selenium 4.0.6, Selenium can download and handle the webdriver automatically. Huzzah!
Until, I bring a new release you can degrade to 4.0.9 or lower, or just remove the argument from your local code  for now.

**Comment by timelyart** [comment]
So, I didn't get the auto download webdriver feature to work on Linux with Selenium 4.10. Unsure, why. I used a new environment so I doubt that is the issue. Could be a permission thing. It is a fairly new feature so it may need some refinement. 

So, if you are on Linux you will still need to download the webdriver yourself and provide the path in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/v3.12/_kairos.cfg). I don't know if the auto download feature will work on OSX. 

@mrcrdwd  would you be so kind as to test this and give me feedback by commenting out `path` in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/v3.12/_kairos.cfg)?

**Comment by mrcrdwd** [comment]
@timelyart Sure, no problem. So what's the exact scenario that you want me to test?

**Comment by timelyart** [comment]
> @timelyart Sure, no problem. So what's the exact scenario that you want me to test?

Just to make sure that Kairos works at all on OSX when the `path` to the webdriver is not set, i.e. does the auto  download and handling of webdrivers by Selenium work at all on OSX.

**Comment by enyan0** [comment]
I did test downgrading selenium on linux and the webdriver works with path, using selenium 4.9. I will reinstall to make sure, as pip list still showing selenium 4.10, and report back.

**Comment by timelyart** [comment]
> I did test downgrading selenium on linux and the webdriver works with path, using selenium 4.9. I will reinstall to make sure, as pip list still showing selenium 4.10, and report back.

No, need to downgrade any longer. Kairos will work with Selenium 4.10 on Linux as long as you have downloaded chromedriver yourself and set it's path (as it used to be).

**Comment by timelyart** [comment]
I take it, Kairos is working as expected and I can close this issue. 
If not, please re-open.

One last thing: I'd be grateful to anyone  that can confirm Kairos is working on a command line only device like a VPS. Please, let me know!

**Comment by enyan0** [comment]
sorry for the late reply. So yes, it works on linux (vmware gui-based). However, running on linux, chrome/webdriver does not render properly (chrome window is a blank white page -- but chrome works fine if I run it on its own regularly). Not a big issue as kairos still works fine, read charts data and exports files, but interacting manually with the page is not possible (so no manual tick on the remember me box - again not a big deal but certain scenarios are not possible, for example where you want to stay logged and need to tick the remember me box and but also want have the extension as a fall back if you get logged out for some reason).

**Comment by timelyart** [comment]
You may need to install additional dependencies and backends. 

From the [PyVirtualDisplay readme](https://github.com/ponty/PyVirtualDisplay/blob/3.0/README.md#installation):

```
$ sudo apt-get install xvfb xserver-xephyr tigervnc-standalone-server x11-utils gnumeric
$ python3 -m pip install pyvirtualdisplay pillow EasyProcess
```

Let me know if this has worked for you.
