### ISSUE TITLE
Summary config file 

### ISSUE THREAD

**Issue by timelyart** [timelyart/Kairos#11]
**Is your feature request related to a problem? Please describe.**
Additional features for sending a summary mail. 

**Describe the solution you'd like**
A config file that can be used from command line as an input for the summary mail. The config file should have the following options:

- to: list of email addresses to send the summary to. One mail will be generated per email address (server limits may apply; see #8 Email forwarding)
- subject: the subject of the mail to be send (see #9)
- html: user defined html. To include alerts into the html use the word %alert (see #7).
- text: user defined text. To include alerts into the html use the word %alert (see #7).
 
**Describe alternatives you've considered**
NA

**Additional context**
See issues: #7  Include HTML in summary, #8 Email forwarding, and #9 Summary subject configurable.

**Comment by ElSeidy** [comment]
https://docs.python.org/2/library/email-examples.html

**Comment by timelyart** [comment]
> https://docs.python.org/2/library/email-examples.html

SMTP is already used for both reading and sending email. Thank you for the tip anyway.

**Comment by timelyart** [comment]
Implementend in version **[v1.1.0](https://github.com/timelyart/Kairos/releases/tag/v1.1.0)**
