### ISSUE TITLE
TV error - trying to export data

### ISSUE THREAD

**Issue by jerajx** [timelyart/Kairos#114]
**Describe the bug**
I'm sendig the console log. I' cant get to exporting the data. I'm also sending you the cfg files. 
[kairos error.zip](https://github.com/timelyart/Kairos/files/13413813/kairos.error.zip)

**To Reproduce**
I have a watchlist in tradingview and would like to export data for all the tickers in that watchlist

**Expected behavior**
at the moment when I would expect the first file to show up in the export folder it just stops and returns error. Login, Catpcha workig well.

**Screenshots**
nothing to be seen on the screenshot that is generated upon error

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11 (both tested, same results)
 - Browser Chrome
 - Version 119

**Additional context**

**Comment by timelyart** [comment]
Thank you for your report. I will start working on it later today.

**Comment by timelyart** [comment]
TV put the data window and object tree under one tab. I will make the necessary selector changes.

**Comment by timelyart** [comment]
Fixed in [release v3.14](https://github.com/timelyart/Kairos/releases/tag/v3.14)

**Comment by jerajx** [comment]
Thank you very much. It works fine now!

Best regards,
Marko


V V tor., 21. nov. 2023 ob 21:45 je oseba timelyart <
***@***.***> napisala:
