### ISSUE TITLE
Please update Chrome browser. Chrome failed to start: exited normally ERROR

### ISSUE THREAD

**Issue by debonair99** [timelyart/Kairos#115]
Using Chrome 121.0.6167.86
Chromedriver https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/win64/chromedriver-win64.zip
Have just started using Kairos again
Screenshot of error attached
Please assist
![Untitled](https://github.com/timelyart/Kairos/assets/85971842/5ef61dbb-2b44-4a14-8b4e-bff31d21e5c4)

**Comment by debonair99** [comment]
Above issue resolves if closing Chrome browser.
Another issue presents
![Untitled](https://github.com/timelyart/Kairos/assets/85971842/ca6d1222-121f-4eba-9e90-e8f3fc4d2519)

**Comment by timelyart** [comment]
Hi & welcome back! 👋

If you want to run Kairos whilst using Chrome for yourself, you'll need to set `share_user_data = true` in your [kairos.cfg](https://github.com/timelyart/Kairos/blob/master/_kairos.cfg). If you run into problems, you might want to try to clear the assigned Chrome data directory by running the following command from your Kairos installation directory:
```
python main.py -cls
```

Your second error seems to come from a failed captcha with manual input. TV has been using captcha for the past year, or so. This came as a surprise to me as (re-)captcha has been discontinued by Google. 
I recommend installing a Chrome extension that solves the (re-)captcha automatically, such as: **NopeCHA** or **MiniRPA CAPTCHA Solver**. 

Please, let me know whether your issue has been solved.

**Comment by debonair99** [comment]
Thank you for getting back to me.
I assume I'm doing something wrong but am unsure what it is.
If i run Kairos in the background this is the error I get:
![image](https://github.com/timelyart/Kairos/assets/85971842/557d2610-ef4d-4ce4-9f63-0175511f14ed)

If I don't run it in the background this is what happens after I try and do the CAPTCHA manually
![image](https://github.com/timelyart/Kairos/assets/85971842/d778b99c-1b7b-4928-b44e-1027aac6e631)

I have installed MiniRPA captcha and it doesn't appear to work when I use Kairos. If I try and login into TradingView myself seperate to Kairos, the MiniRPA does work.

Thanks

**Comment by debonair99** [comment]
Thanks for getting back to me!
I'm doing something wrong but am unsure what it is!
I have installed CAPTCHA solver and it doesn't seem to work when running Kairos. When I try and log into TradingView without Kairos it does the CAPTCHA automatically.

If I run Kairos in the background:
![image](https://github.com/timelyart/Kairos/assets/85971842/cf1638c0-8134-46f1-ac3e-f1193e4b4e8e)

If I don't run in the background and try and complete the CAPTCHA manually:
![image](https://github.com/timelyart/Kairos/assets/85971842/40763ca2-3711-40d2-ac8e-4b3a7c262d31)

Thank you for your help

**Comment by timelyart** [comment]
My apologies for answering this late. Unfortunately, life got in the way. 

Try `python main.py -cls` once more. Kairos might have copied your Chrome user data folder before you installed the CAPTCHA solver.

If you get the same error, please let me know and share any screenshots Kairos makes (be mindful of private stuff please).

**Comment by debonair99** [comment]
Removed user_data_directory in .cfg file and issue resolved
