### ISSUE TITLE
No signals triggered. Nothing to send. Error?

### ISSUE THREAD

**Issue by jerajx** [timelyart/Kairos#116]
**Describe the bug**
I'm trying to run the yaml script - like Browse or export.yaml

The script logs in, captcha ok, and it loads the chart. 

the next move should be to open the watchlist and do something with it (just browse over it or export the data...). It seem that it can't open the watchlist. 

after a short delay it writes 
No alerts or signals set
No signals triggered. Nothing to send
and quits.

I'm doing something wrong?

**To Reproduce**

run the script browse.yaml or export.yaml

**Expected behavior**
I would expect the script to open the watchlist and browse throug it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 125.0
 - Version 125.0 + cromedriver the same

**Additional context**
I'm attaching the logs from the terminal window using loggin=20 and 10 seperatedly
[browse.yaml.tmp.txt](https://github.com/user-attachments/files/15516980/browse.yaml.tmp.txt)
[terminal logging=10.txt](https://github.com/user-attachments/files/15516981/terminal.logging.10.txt)
[terminal logging=20.txt](https://github.com/user-attachments/files/15516983/terminal.logging.20.txt)

**Comment by timelyart** [comment]
Thank you for taking the time to report. 

Every so often TV is "improving" the website and elements of it get renamed or moved around. That is probably what is happening here. I'll look into it this week and expect to have a patch ready on Friday at the latest.

**Comment by jerajx** [comment]
Understood, thanks
Best regards,
Marko

V pon., 3. jun. 2024, 15:04 je oseba timelyart ***@***.***>
napisala:

**Comment by timelyart** [comment]
Fixed in [release v3.15](https://github.com/timelyart/Kairos/releases/tag/v3.15).

If you still encounter problems, please reopen this issue.

**Comment by jerajx** [comment]
thank you, works like a charm.
Best regards,
Marko

V V pet., 7. jun. 2024 ob 12:20 je oseba timelyart ***@***.***>
napisala:

**Comment by jerajx** [comment]
Hi, 
There is the same problem again (Kairos v 3.16), chrome + cromedriver 128.0.6613, windows 11.
When it comes to opening the watchlist closes with the following:

2024-09-04 11:25:42.745 INFO tv - run: No alerts or signals set
2024-09-04 11:25:42.745 INFO tv - run: No signals triggered. Nothing to send

**Comment by timelyart** [comment]
I know I said you may re-open this issue if you still had problems but this issue was solved at the time. So, when the same issue arises again after it was initially solved please create a new issue for it so I can link the problem (i.e. issue number) with the solution (i.e. release version). 

That being said, it is fixed in [release v3.17](https://github.com/timelyart/Kairos/releases/tag/v3.17). This release also enables you to automatically update the webdriver for Chrome (see release notes).

**Comment by jerajx** [comment]
Thank you, it is working now.
Best regards,
Marko

V V sob., 7. sep. 2024 ob 14:49 je oseba timelyart ***@***.***>
napisala:
