### ISSUE TITLE
Chart not opening error and corresponding message of no signals set

### ISSUE THREAD

**Issue by debonair99** [timelyart/Kairos#117]
Tried using latest version of Kairos with the below screenshots when running

![1](https://github.com/timelyart/Kairos/assets/85971842/92991da4-d6fd-4158-9b68-ce973dfb8d0e)
![2](https://github.com/timelyart/Kairos/assets/85971842/77195590-ea4d-4fe6-aba4-0f68df670f3e)

Please assist, I have tried using StockOverflow but to no avail
Thanks!

**Comment by jerajx** [comment]
Hi, I have the same problem. It seems it stucks when opening the wachlist.

**Comment by timelyart** [comment]
Probably something in the DOM changed. I'll try to get a fix in within a week.

**Comment by timelyart** [comment]
Well... I don't know what to say. I have no issues. It might be that the DOM changes haven't been rolled out to the server that serves me. This has happened in the past. All I can do is wait until it starts breaking for me as well. 

I did notice you have a lower `DELAY_KEYSTROKE` at 0.01 than my 0.05. So, you might try a higher value. Can you tell what you were trying to do? Setting alerts? Back testing strategies? Or, triggering signals?

**Comment by jerajx** [comment]
DELAY_KEYSTROKE at 0.01 is default, anyway I changed it to 0.05, no change. I'm attaching some logs. I tried export and browse.yaml. Logs are from browse. script logs in OK, and then stops when it should open the watchlist.

[browse-log10.txt](https://github.com/user-attachments/files/16357741/browse-log10.txt)

[browse-log20.txt](https://github.com/user-attachments/files/16357753/browse-log20.txt)

**Comment by timelyart** [comment]
Thank you for giving the additional information. 

The only thing I can think of now is to clear your browser cache, run `python main.py -cls` and run Kairos as you would do normally (in that order). This makes sure the cache gets purged from the Kairos Chrome container. 
Let me know whether this solves the issue.

**Comment by jerajx** [comment]
I did that before, this doesn't help.

V V sre., 24. jul. 2024 ob 11:50 je oseba timelyart <
***@***.***> napisala:

**Comment by timelyart** [comment]
In that case... we just have to wait until the DOM changes for me as well which will hopefully be sooner than later. I'll check it daily.

**Comment by timelyart** [comment]
Fixed in [v3.16](https://github.com/timelyart/Kairos/releases/tag/v3.16).

**Comment by jerajx** [comment]
Yes, it works!
Thank you!

V V pet., 26. jul. 2024 ob 17:58 je oseba timelyart <
***@***.***> napisala:

**Comment by johnmolino** [comment]
broke again?

**Comment by jerajx** [comment]
Kairos 3.17 works fine here (win11, chrome 128.0.6613)


V V sre., 11. sep. 2024 ob 03:35 je oseba John Molino <
***@***.***> napisala:

**Comment by timelyart** [comment]
> broke again?

Are you running [v3.17](https://github.com/timelyart/Kairos/releases/tag/v3.17)?
