### ISSUE TITLE
Feature idea - Discord webhook suport

### ISSUE THREAD

**Issue by alexpunct** [timelyart/Kairos#16]
Context: Recently I wanted to setup a new webhook with Discord but it seems they expect a specific data structure so the message is not being received by their API. 

Feature: As a Kairos user I want to be able to wrap the webhook data into a specific data structure so it's accepted by the Discord webhook. The JSON [data structure for Discord webhook](https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9) should look something like this:

```
{
  "username": "{{TICKER}} Signal",
  "embeds": [
    {
      "title":  "{{TICKER}} {{SIGNAL_TIMEFRAME}} {{SIGNAL_NAME}}",
      "url": "{{CHART_URL}}",
      "color": 15258703,
      "fields": [
        {
          "name": "Entry",
          "value": "{{SIGNAL_ENTRY}}",
          "inline": true
        },
        {
          "name": "Stop",
          "value": "{{SIGNAL_STOP}}",
          "inline": true
        },
        {
          "name": "Stop",
          "value": "{{SIGNAL_TARGET}}",
          "inline": true
        }
      ],
      "thumbnail": {
        "url": "{{SCREENSHOT_URL}}"
      },
      "image": {
        "url": "{{SCREENSHOT_URL}}"
      }
    }
  ]
}
```
If we could configure it, even better maybe in a yaml using the field names we already have. But that's for later, if it could just have this one in the meantime that would be great.

Thanks!

**Comment by timelyart** [comment]
Is there a way to send multiple signals at once? If so, can you provide the JSON for that?

**Comment by alexbejan-mavfarm** [comment]
> Is there a way to send multiple signals at once? If so, can you provide the JSON for that?

I don't think that's possible. Can you fire a request for each? The alternative would be to change the data structure and put the signals in the `fields`

**Comment by timelyart** [comment]
**embeds** seems to be meant to include multiple signals since it's a list - can you check for me if that is the case
Making a request for each signal is really sub optimal and there is a serious risk that Discord will introduce limits.

It's actually quite difficult to come to a neat solution since Kairos doesn't know which part of the user defined JSON template is meant to hold the collection of signals. I think I'll make it so that Kairos assumes the first list encountered in the template holds the signals.

**Comment by alexpunct** [comment]
Hehe, I already checked that's why I was saying to put it under fields. Seems like if you put multiple objects in embed it only outputs one. In any case, I've written a simple web api that transforms the Kairos and converts them to Discord requests, so let's park this for now unless anybody else will be interested.

**Comment by timelyart** [comment]
JSON template support was added in [v2.39](https://github.com/timelyart/Kairos/releases/tag/v2.39)
