### ISSUE TITLE
Webhook URL won't set

### ISSUE THREAD

**Issue by willseo08** [timelyart/Kairos#18]
Even though I set the webhook URL in my alert.yaml, the Webhook URL box on alerts is not checked and my URL is not inputted. Any ideas? In the alerts > send portion of the alert.yaml, I see that there is no webhook URL field.

**Comment by timelyart** [comment]
Sending alerts to webhooks is a recent addition TV alerts; I largely use 'signals' to scan and generate webhook data on higher time frames. So, I never bothered updating the alert.yaml example file. Kairos does support it.

Try:
```
alerts:
- name: "My Awesome Setup"
  ...
  # URL to send alert text to a webhook (if any)
  webhook: "https://someurl.to/webhook"
  ...
```

Let me know if this solved it for you.

**Comment by timelyart** [comment]
Closing this issue since I haven't heard back.
