### ISSUE TITLE
Add horizontal lines

### ISSUE THREAD

**Issue by willseo08** [timelyart/Kairos#19]
It would be great to be able to define a level at which you'd like a horizontal line drawn and specifiy the color. Oftentimes I have tons of levels written down and just want to be able to mass draw them on a chart.

**Comment by timelyart** [comment]
TradingView would be the place to do so. I suggest you take a look at their Pine script and what is already available through their  Pine script library. Generally speaking TradingView does your charting and Kairos handles everything else such as making watchlists, setting alerts and automatic trading through webhooks.
