### ISSUE TITLE
Different chart layout for screenshots

### ISSUE THREAD

**Issue by khurramrehmani** [timelyart/Kairos#2]
As a user, I would like that my screenshots show me a bigger picture of the asset I'm considering so I would like to see multiple time frames. 

Solution: allow me to specify a separate screenshot Tradingview chart layout URL and use that when taking the screenshot. This way I can have one layout for the analysis and alert and another one for reporting. 

Thanks!

**Comment by timelyart** [comment]
Well, if I'm going to include this option I might as well make it into a list and then you can add as many screenshots of different charts as you want.

**Comment by timelyart** [comment]
Added in [release v1.0.13](https://github.com/timelyart/Kairos/releases/tag/v1.013)
