### ISSUE TITLE
Alerts are set to open ended

### ISSUE THREAD

**Issue by alexpunct** [timelyart/Kairos#2]
It seems after the last update the alerts are set as open ended so I quickly run over the limit

**Comment by timelyart** [comment]
Fixed in [v1.2.7](https://github.com/timelyart/Kairos/releases/tag/v1.2.7). Thanks Alex for reporting and the help fixing it.

**Comment by timelyart** [comment]
Fixed in [v1.2.7](https://github.com/timelyart/Kairos/releases/tag/v1.2.7). Thanks Alex for reporting and the help fixing it.
