### ISSUE TITLE
Strategy Yaml: element not interactable

### ISSUE THREAD

**Issue by kinhunt** [timelyart/Kairos#20]
**Describe the bug**
Trying to run backtests with the strategies.yaml. It gives this error:

retry_back_test_strategy_symbol: Message: element not interactable

**To Reproduce**
1. copy _strategies.yaml to strategies.yaml
2. change chart id, watch list name and strategy name
3. remove input and properties, use default ones
4. run script
5. login success, open chart success, choose watchlist success
6. error: 'retry_back_test_strategy_symbol: Message: element not interactable'

**Expected behavior**
Run tests and report back.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version Chrome 88

**Comment by timelyart** [comment]
Thank you for reporting. I will investigate and prepare a fix.

**Comment by timelyart** [comment]
Fixed in [v2.42](https://github.com/timelyart/Kairos/releases/tag/v2.42)
