### ISSUE TITLE
Unable to login to tradingview

### ISSUE THREAD

**Issue by cgssierra-git** [timelyart/Kairos#24]
Hi Timely Art,

I am logging this as not a bug, because I am not really sure if its a bug or their something I am doing wrong.  When I login to Kairos I am getting a message "logged in under a different username at tradingview.com". I will really appreciate if you can help me and tell me if there is something I am not doing correctly.

Error snippets:
DevTools listening on ws://127.0.0.1:59932/devtools/browser/ee7b24af-28ea-4281-a05a-4ce9d8d786a9
2021-07-26 11:27:34.037 INFO tv - check_driver: browser version: 92.0.4515.107
2021-07-26 11:27:34.037 INFO tv - check_driver: driver version: 91.0.4472.101
type your TradingView password and press enter:
2021-07-26 11:27:57.458 WARNING tv - login: logged in under a different username at tradingview.com
2021-07-26 11:28:07.649 ERROR tv - login: Message:

2021-07-26 11:28:09.347 ERROR tv - snapshot: log\20210726_112807.png

![image](https://user-images.githubusercontent.com/52270565/126930243-7792a609-1ded-4c01-b819-348dff72f2a4.png)

**Comment by cgssierra-git** [comment]
I debug the code and find out what was obvious :), Awesome code! I will surely help to spread the wings! Keep it up!

**Comment by timelyart** [comment]
What was the issue?

**Comment by cgssierra-git** [comment]
I have login using my email address, hence it display the whole email on my trading account and Kairos is detecting it as different user. I have login with just the username and it work.

Feature suggestion: It will also be nice if we can create an alert, with the alert condition as the strategy or pine scripts.

**Comment by timelyart** [comment]
> 
> 
> I have login using my email address, hence it display the whole email on my trading account and Kairos is detecting it as different user. I have login with just the username and it work.
> 
Ah, right. Never thought of that. I don't think I can improve that without going through the hassle of checking the email on the account. Seems not worth it as it will slow down the process of logging in and complicate the code.
>
>
> Feature suggestion: It will also be nice if we can create an alert, with the alert condition as the strategy or pine scripts.
>
You should be able to do this already. From the [_alerts.yaml](https://github.com/timelyart/Kairos/blob/master/yaml/_alert.yaml) example file:
```
    # Kairos tries to find conditions based upon the values you provide below.
    # Set the conditions as you would do manually in order from left to right and from top to bottom
    # It is sufficient to only set the first word for each condition.
    conditions: ["Golden", "Plot", "Crossing Up", "Golden", "Plot"]
```
You can rewrite this to:
```
    conditions: ["MY STRAT"]
```
The `conditions` keyword is of dynamic length. You simply put as many conditions in as there are selection boxes on the alert. 
Let me know if this helps you.

**Comment by cgssierra-git** [comment]
Hi Timely Art,

I tried that, but it was getting errors, but when I comment out the options 1-3 in tv.py; then it works.

Regards,
Christian
________________________________

**Comment by timelyart** [comment]
Ah. Thanks for sharing that. I guess that is a bug then. Please see #25 to keep track.

Closing this issue.
