### ISSUE TITLE
allow message text in json format

### ISSUE THREAD

**Issue by JanAbraham** [timelyart/Kairos#27]
Hi, I am trying to use Kairos for creating alerts for sending them to a webhook target. To allow higher security 'Post' method is preferred from 'Get' mode. However, POST requires JSON format, which has special signs like " included. When I use that in the message in Kairos, it produces an error.

Is ther a possibility to support message texts in json format?

Many thanks in advance,
Jan

**Comment by timelyart** [comment]
First of all can you share the error from your `.log` file and the message you were trying to send? Please, make sure that you don't share any privacy sensitive information in the process.

Although, I have tested webhooks for alerts at a basic level. I never tested alerts with webhooks in a production environment. 
I will look into it. This week I am a bit hard pressed though. 

In the mean time, have a look at how signals work. Depending on what you are trying to do they may very well fulfil your needs.

**Comment by JanAbraham** [comment]
the error msg is: (complete log is attached)
- in "yaml/alert_Zignaly_Spot.yaml", line 70, column 15
- 2021-08-19 13:31:02.089 ERROR tv - run: argument of type 'NoneType' is not iterable
[alert_Zignaly_Spot.yaml.log](https://github.com/timelyart/Kairos/files/7014046/alert_Zignaly_Spot.yaml.log)

here is the corresponding line in the yaml file:
      text: ""{"key":"<API Key>","exchange":"{{exchange}}","pair":"{{ticker}}","type":"entry","ordertype":"limit","signalid":"{{ticker}}","positionSizePercentage":"1","buyTTL":"540","takeProfitPercentage1":"0.6"}""

I checked the signals part you recommended, however that is not a valuable replacement for the way I am using alerts with webhooks. But thanks for the advice!

**Comment by timelyart** [comment]
You can encapsulate the whole string in single quotes `'` like this:
`text: '""{"key":"","exchange":"{{exchange}}","pair":"{{ticker}}","type":"entry","ordertype":"limit","signalid":"{{ticker}}","positionSizePercentage":"1","buyTTL":"540","takeProfitPercentage1":"0.6"}""'`

Please let me know if this solved it for you.

**Comment by JanAbraham** [comment]
That was the solution. Now there is no error anymore :-)

However ... the webhook entry is not showing in the alert, neither does the alert message for the webhook. Screenshot from the moment when Kairos wants to fill the fields is attached. My assumption is that for the alert message to be filled, the screen needs to be scrolled down. I tried with different resolutions and with run-in-background, but without success. Any ideas?
<img width="443" alt="Screenshot 2021-08-19 at 22 04 26" src="https://user-images.githubusercontent.com/25281780/130136819-eafe006d-b961-4bcb-8f59-35d6b9100aab.png">


maybe some helpful background: I am running Kairos on a MacOS system, not on windows.

**Comment by timelyart** [comment]
Kairos runs by default at a resolution of 1080p. What resolution are you using on your system and what is the value for `resolution` in your `kairos.cfg`?

This really shouldn't happen. The only thing I can think of is, is that the browser is not (or no longer) running at 1080p.

**Comment by JanAbraham** [comment]
That might be it with the resolution.

Unfortunately, I am not able to change the resolution of 1080p or ratio  to 16:9 on my Macbook Air. Tried different ways and tools. Tried with higher resolutions as well. Next I will try to connect an external monitor and lets see if that works out.

**Comment by timelyart** [comment]
You can try to run Kairos in 'background' mode. Although, I am unsure whether Kairos would run virtually in 1080p on a lower resolution display. It is worth a shot. 

Unfortunately, it isn't really worth it to try to fix this for lower resolutions as you will undoubtedly encounter more issues of the same kind. 

I recommend getting a dedicated (virtual) server to run Kairos periodically from unless you only want to set alerts once for a list of markets which size does not go beyond the limits of your account.

**Comment by JanAbraham** [comment]
After experimenting around and finally changing to a windows PC, I am able to run it through and alerts including the alert text are being created :-)

Still, there are 2 issues, which I hope you can help me with:
1. the webhook is not activated and the url is not given: is this supposed to be done by Kairos? After viewing all your videos, I am not so sure anymore ... But it is essential for me to have this working. In case it is not yet part of Kairos, can it be added?
2. the Alert text contains "screenshots_to_include: []". Is that normal? Since my webhook target is not expecting this, it would lead to issues when an alert is triggered and sent to the webhook.

Many thanks in advance!
Jan

<img width="411" alt="Screenshot 2021-08-27 at 13 27 42" src="https://user-images.githubusercontent.com/25281780/131121277-6ff8e6fb-4c2a-4ab0-90b0-11b0ab0d6bad.png">

**Comment by timelyart** [comment]
Bear in mind that those instructional videos were shot at a time when webhooks were not available yet. This will be an ongoing issue as TV changes things around and adds stuff. 
> 1. the webhook is not activated and the url is not given: is this supposed to be done by Kairos? After viewing all your videos, I am not so sure anymore ... But it is essential for me to have this working. In case it is not yet part of Kairos, can it be added?

Kairos should set the webhook url. However, what may have changed is that TV now memorizes the value from the previous session and doesn't override the existing value with the new one. Is that what happens?
> 2. the Alert text contains "screenshots_to_include: []". Is that normal? Since my webhook target is not expecting this, it would lead to issues when an alert is triggered and sent to the webhook.

Now, this line definitely should not be set. Try removing the `screenshots_to_include` line from your YAML.

**Comment by timelyart** [comment]
> > 1. the webhook is not activated and the url is not given: is this supposed to be done by Kairos? After viewing all your videos, I am not so sure anymore ... But it is essential for me to have this working. In case it is not yet part of Kairos, can it be added?
>
> Kairos should set the webhook url. However, what may have changed is that TV now memorizes the value from the previous session and doesn't override the existing value with the new one. Is that what happens?

I checked this. Kairos is behaving exactly how it should. Did you successfully connect to Zignaly using a test program like Postman?
> > 1. the Alert text contains "screenshots_to_include: []". Is that normal? Since my webhook target is not expecting this, it would lead to issues when an alert is triggered and sent to the webhook.
> 
> Now, this line definitely should not be set. Try removing the `screenshots_to_include` line from your YAML.

Fixed in [latest release](https://github.com/timelyart/Kairos/releases/tag/v2.52).
Let me know if you were able to connect to Zignaly using the TV alert webhook.

**Comment by timelyart** [comment]
Haven't heard back in a week, so I assume that it is solved. Don't hesitate to let it be known that problems still persist.
