### ISSUE TITLE
Proposal for new functionality - export chart data

### ISSUE THREAD

**Issue by jerajx** [timelyart/Kairos#30]
Hi,
I have to export the chart data for each ticker in the watch list with the built-in function (Menu - Export chart data ...), which is a painstaking process for larger watch lists.

- Only the data displayed on the screen seems to be exported with the built-in export function, so the chart should be compressed as much as possible to get as much data as possible (or you can do this using parameters and retrieve data for a predetermined period of time)
- Exported chart data must include standard data (open, high, low, closed, vol and all plotted data within the indicator and strategies used) - the built-in function works fine, so it doesn't need to be changed in any way.

Parameters:
- study or strategy used (one or more of both) [optional]
- time period (from date to date) [default: maximum possible]
- time frame [default: 1 day]
- Watch list - Export each tag in the watchlist one by one and save the CSV to disk (or Google Drive)
- time format (ISO time or UNIX timestamp) default [ISO time] - this is the parameter to be selected when the pop-up window opens.
- the path where the CSVs are stored
- Delay - For slow internet connections, the delay for the chart to load successfully before downloading.

The result is the number of CSVs in the folder on disk (one for each ticker in the watchlist). The CSV name is already defined in the built-in function, it does not need to be changed.

Thank you so much for your time and effort!
-Marko

**Comment by timelyart** [comment]
Export of data is supported as of [release v2.55](https://github.com/timelyart/Kairos/releases/tag/v2.55).

There is one limitation though. Kairos cannot control the download dialogue (for good reasons). 
However, you can set a destination directory for downloaded files in **kairos.cfg** and in YAML files (overrides _kairos,.cfg_).
Please have a look at the example file [_export.yaml](https://github.com/timelyart/Kairos/blob/v2.55/yaml/_export.yaml).

Testing did not reveal that delays are warranted. In the case you do encounter problems with either delays or otherwise then please feel fee to open a new issue.

**Comment by jerajx** [comment]
Awesome, this was express fast! anyway there is still an issue. I works for a number of tickers and than it stops. The number is not always the same. Maybe the problem is slow internet connection. I'm attaching the console_log file and a shapshot.
![20211102_080542](https://user-images.githubusercontent.com/88029105/139802459-3df121d6-4c16-41f7-b972-3ad3c272ba24.png)
[log console 02-11-2021.txt](https://github.com/timelyart/Kairos/files/7458523/log.console.02-11-2021.txt)

**Comment by jerajx** [comment]
`<div class="tv-dialog__modal-body"><div class="tv-dialog js-dialog i-focused" tabindex="-1" style="width: 100%; max-width: 500px;"><div class="tv-dialog__section tv-dialog__section--title js-dialog__drag"><div class="js-title-text tv-dialog__title">Oops, something went wrong</div></div><div class="tv-dialog__section tv-dialog__section--no-border tv-dialog__section--no-padding_bottom"><div class="tv-text tv-text--position-outside">Please report the issue or click Reconnect.</div></div><div class="tv-dialog__section tv-dialog__section--actions tv-dialog__section--actions-adaptive tv-dialog__section--no-border"><div data-name="report" class="js-dialog__action-click js-dialog__no-drag tv-button tv-button--primary">Report a data issue</div><div data-name="reconnect" class="js-dialog__action-click js-dialog__no-drag tv-button tv-button--primary">Reconnect</div></div><div class="tv-dialog__close js-dialog__close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 13 13" width="13" height="13"><path fill="currentColor" d="M5.18 6.6L1.3 2.7.6 2 2 .59l.7.7 3.9 3.9 3.89-3.9.7-.7L12.61 2l-.71.7L8 6.6l3.89 3.89.7.7-1.4 1.42-.71-.71L6.58 8 2.72 11.9l-.71.7-1.41-1.4.7-.71 3.9-3.9z"></path></svg></div></div></div>`
