### ISSUE TITLE
Search function in screener to watchlist doesn't filter the results

### ISSUE THREAD

**Issue by jlee462** [timelyart/Kairos#33]
**Describe the bug**
The script is successfully typing the search criteria that was set in the YAML file in the search box on the screener, but the screener is not updating the results. When I replicate this manually in Chrome, it works fine. I am not sure why the result set is not updating.

I have fast internet and I changed the DELAY_SCREENER_SEARCH to 15. I do not think it is because of internet lag, but I can't figure out why it isn't filtering because I can see it typing the search criteria in the shell.

**Screenshots**
I recorded a video on Youtube to show the behavior
https://youtu.be/kr-wnATHEjw

**Desktop (please complete the following information):**
 - OS: OSX 12.0
 - Browser Chrome
 - Version 95.0.4638.69 

You are amazing!!!!! Thank you, thank you, thank you!!!!

**Comment by timelyart** [comment]
Yes. This is something I encountered as well while I was adding the 'export chart data' functionality. Their new implementation with the dialog in front is much much worse than it was before where you could simply enter the ticker in the box. 

I understand why they did this but there is not a really good way to fix this without a significant loss in performance which is why I haven't done so already. I need to think about what the least detrimental fix is.

**Comment by timelyart** [comment]
> Yes. This is something I encountered as well while I was adding the 'export chart data' functionality. Their new implementation with the dialog in front is much much worse than it was before where you could simply enter the ticker in the box.
> 
> I understand why they did this but there is not a really good way to fix this without a significant loss in performance which is why I haven't done so already. I need to think about what the least detrimental fix is.

Scratch this. The issue I encountered differs from yours. I thought you were speaking of changing the ticker on the chart and then exporting the data.

I wasn't able to reproduce your issue on Windows. It may be an issue related on how Chrome works on Mac. Unfortunately, I don't own a Mac and I am unable to fix this. You might try to set `clipboard = false` in your **kairos.cfg**.

I will try to reproduce the error on Linux as well and report my findings here.

**Comment by timelyart** [comment]
One more question.... if you hit enter after the search box is set with 'usd' does it update then?

**Comment by jlee462** [comment]
I'll try that later this evening. There is no enter required when you use Tradingview in Chrome.It automatically updates as you type which seems to be your expected behavior. 

Random question. Do you know the lookback period of the screener? I get questionable results from it at times. I also find it weird that it never displays the USDT pairs for exchanges like KuCoin.

**Comment by timelyart** [comment]
> Random question. Do you know the lookback period of the screener? I get questionable results from it at times. I also find it weird that it never displays the USDT pairs for exchanges like KuCoin.

If you are trying to find the lookback period on indicators you can hover over the title and it should tell you what settings they use.
I just looked (manually) at USDT pairs on Kucoin with no problem. So, I don't know.

**Comment by timelyart** [comment]
So, I tested it in Linux and didn't encounter any issues. 

Unless, someone with a Mac can reproduce this and provide a fix there is not much I can do.

**Comment by jlee462** [comment]
> So, I tested it in Linux and didn't encounter any issues.
> 
> Unless, someone with a Mac can reproduce this and provide a fix there is not much I can do.

I can do a screen share and we can go through this together if you want. I can also try it another Mac but can't get to it until next week

**Comment by jlee462** [comment]
I loaded up another test I did that might be helpful.

https://youtu.be/ajPBgTB6tGw

**Comment by timelyart** [comment]
I have no doubt it can be reproduced on Macs but there is no way for me to fix it. That is what I mean by someone who does have a Mac providing a fix.

**Comment by timelyart** [comment]
So, after viewing your test I may have a fix but it is a guess really. A possible fix could be to click the search box first so it has focus. I can see why it would not register the value set in the box.

Before I go and alter the code... did you set `clipboard = false` as I requested earlier?

**Comment by jlee462** [comment]
sorry, I forgot. I tested that and it worked, but it now types the search command twice.

https://www.youtube.com/watch?v=xzpViF-EKI8

**Comment by timelyart** [comment]
You are running the latest version?

**Comment by jlee462** [comment]
The latest version works. Thank you.
