### ISSUE TITLE
Backtest input values not being modified

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#36]
My backtest runs and outputs a result but the input values aren't in line with what has been specified in strategies.yaml. I have tried using different input labels but with no success. There are quite a few 404 errors in my log so I'm not sure which one to pay attention to.

**Comment by timelyart** [comment]
Testing revealed that the DOM for checkboxes must have changed. 

Apart from the checkboxes, are the other values in line with your YAML?

**Comment by timelyart** [comment]
Seems that checkboxes and select boxes were changed. Working on a fix.

**Comment by timelyart** [comment]
Fixed in [release v2.61](https://github.com/timelyart/Kairos/releases/tag/v2.61).
