### ISSUE TITLE
set_indicator_dialog_values error

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#38]
Backtesting strategies using v2.61 results in this error:

```
2021-11-13 12:18:03.451 ERROR tv - set_indicator_dialog_values: startswith first arg must be str or a tuple of str, not int
Traceback (most recent call last):
  File "/kairos/tv/tv.py", line 4213, in set_indicator_dialog_values
    if (title == key) or ((not EXACT_CONDITIONS) and title.startswith(key)):
TypeError: startswith first arg must be str or a tuple of str, not int
```

**Comment by timelyart** [comment]
Can you post the values that correspond to the keys `inputs` and `properties` from your YAML, please?

**Comment by marcfon** [comment]
Okay this error was caused because I forgot to add `[ ]` around comma separated values in the properties field.

**Comment by timelyart** [comment]
Glad you have sorted it out.

**Comment by marcfon** [comment]
A hint in the error message to look for this config mistake might be helpful.
