### ISSUE TITLE
create alerts doesn't work as expected

### ISSUE THREAD

**Issue by jerajx** [timelyart/Kairos#40]
Using the alert.yaml script I get an error. I'd like to input alerts for all tickers in a watchlist using no special alert condition, but instead "Any alert() function call" to be the trigger for alerts. 

I'm attaching the console log and a screenshot. 

[console log 18-11-2021.txt](https://github.com/timelyart/Kairos/files/7560665/console.log.18-11-2021.txt)
![20211118_074142](https://user-images.githubusercontent.com/88029105/142366927-4fd5b665-6641-4b6a-9711-4cd24b0187fe.png)

**Comment by timelyart** [comment]
This behavior only occurred when using "Any alert() function call" and having `message` set in your **YAML file**.
Thank you for pointing it out though. 

Fixed in [release v2.65](https://github.com/timelyart/Kairos/releases/tag/v2.65).

**Comment by jerajx** [comment]
Thank you very much! It works perfectly now!

Don't forget to contact me, when you come to Slovenia, so we can have a
couple of beers together with a Slovenian pizza, which is way better than
the original Italian... not in every pizzeria though, but I know where to
go.

Thanks a lot!
Best regards,
Marko







V V čet., 25. nov. 2021 ob 01:21 je oseba timelyart <
***@***.***> napisala:
