### ISSUE TITLE
Cookie consent popup interferrence

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#44]
The cookie consent popup hijacks the canvas in some situations. Kairos doesn't like it and throws the following error:

`ERROR tv - open_chart: Message: element click intercepted: Element <div class="title-37voAVwR" data-name="backtesting" data-active="false">...</div> is not clickable at point (452, 778). Other element would receive the click: <article class="toast-305jedKL" role="status">...</article>`

Manually clicking the consent popup away gets rid of the error but of course this doesn't work if you're running in the background.

**Comment by timelyart** [comment]
Kairos shouldn't auto-accept cookies imho. 

Log in TV with chrome, click the accept cookies button and you should be good to go. Provided you have set `share_user_data = true` in your **_kairos.cfg_**.

**Comment by marcfon** [comment]
> Log in TV with chrome, click the accept cookies button and you should be good to go. Provided you have set `share_user_data = true` in your **_kairos.cfg_**.

Might be something to add to the FAQ?

I would say accepting cookies isn't a great idea. But it's unfortunate that the consent popup sometime interferes with normal behaviour.

**Comment by marcfon** [comment]
> Log in TV with chrome, click the accept cookies button and you should be good to go. Provided you have set `share_user_data = true` in your **_kairos.cfg_**.

Tried this and it doesn't work (on a mac). The cookie consent from is still showing up in kairos.

The problem is that kairos opens chrome as a guest user profile when you have multiple profiles active in chrome.

Is it possible select a specific user profile in kairos?

Or can it be a configuration option to allow kairos to click the popup away accept cookies?

**Comment by timelyart** [comment]
Fixed in release [v2.74](https://github.com/timelyart/Kairos/releases/tag/v2.74).
