### ISSUE TITLE
Default checkbox values not read correctly

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#47]
Checkbox field values are always returned as `on` in [v2.70].

**Comment by timelyart** [comment]
Fixed with version [v2.72](https://github.com/timelyart/Kairos/releases/tag/v2.72).

**Comment by marcfon** [comment]
Based on the default input and default properties all checkboxes are still read as `on` for me.

Changing the value of checkbox also isn't working yet.

Should checkboxes be set through `on/off`, `true/false` or `0/1`? Or do all these values work?

**Comment by timelyart** [comment]
> Based on the default input and default properties all checkboxes are still read as `on` for me.

You have inputs and/or properties unchecked and they wind up in the `default_inputs/default_properties set` as `yes`?
> Changing the value of checkbox also isn't working yet.

Works on Windows and Linux machines.
> Should checkboxes be set through `on/off`, `true/false` or `0/1`? Or do all these values work?

None of them. You can use one of the following options: `yes/no` (recommended), `'yes'/'no'` or `True/False`

**Comment by marcfon** [comment]
> You have inputs and/or properties unchecked and they wind up in the `default_inputs/default_properties set` as `yes`?

Correct. And to be more precise they are reported back as `on` rather than `yes`.

> None of them. You can use one of the following options: `yes/no` (recommended), `'yes'/'no'` or `True/False`

Maybe I was set on the wrong track by the default values reported back as `on`. I will test with `yes/no`.

**Comment by timelyart** [comment]
That is odd. Checkboxes in the `default_inputs` and `default_properties` sets are reported back as `yes/no` for me. To be certain, you are still getting `on/off` values as of v2.72?

**Comment by marcfon** [comment]
> That is odd. Checkboxes in the `default_inputs` and `default_properties` sets are reported back as `yes/no` for me. To be certain, you are still getting `on/off` values as of v2.72?

I'm on v2.72 and they are reported back to me as `on` even when they aren't checked. I've sent you a screen recording.

**Comment by timelyart** [comment]
Fixed in [version v2.73](https://github.com/timelyart/Kairos/releases/tag/v2.73)
