### ISSUE TITLE
Drop down values not being set in inputs tab by backtest

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#48]
Values of drop down fields aren't set being set in the inputs tab. For instance something like this doesn't work `'name': {0: 'QFL Bot', 1: 'Multi-pair'}` where field 1 is a value in the drop down list

Setting a dropdown value in the properties tab using something like this `properties: {'base_currency': 'EUR'}` does work correctly.

So not sure if the problem is with the dropdown list itself or the fact that in the first example it's part of a multi column field.

**Comment by timelyart** [comment]
Good catch. Fixed in [release v2.71](https://github.com/timelyart/Kairos/releases/tag/v2.71).
