### ISSUE TITLE
Unable to compare 69182.5 of <class 'float'> with 'n/a' of <class 'str'>

### ISSUE THREAD

**Issue by jlee462** [timelyart/Kairos#49]
I am running your signal.yaml to test out signals and I want to fire when an indicator value is not n/a. This is the exact scenario you demo'ed on youtube. When I set the value of the right side to n/a, I get the following error:

2021-12-22 12:45:46.872 WARNING tv - is_indicator_triggered: trying again. Unable to compare 69182.5 of <class 'float'> with 'n/a' of <class 'str'>

The left side is set to the index of the indicator value which returns the BTC price of a Fibonnaci point

**Expected behavior**
I expect that if the value 69182.5 is not n/a, then it should successfully trigger.

**Screenshots**
<img width="1063" alt="Screen Shot 2021-12-22 at 12 53 49 PM" src="https://user-images.githubusercontent.com/3181122/147134980-d2ed44fe-fa39-4f23-b6b3-ee9d2048359a.png">
<img width="1350" alt="Screen Shot 2021-12-22 at 12 59 31 PM" src="https://user-images.githubusercontent.com/3181122/147135607-4d8f8180-90d7-4cc6-a01c-81040414fdf0.png">

**Desktop (please complete the following information):**
 - OS: MacOSX 12.0
 - Browser: Chrome
 - Version: Version 96.0.4664.110

Thank you so much!!!

**Comment by timelyart** [comment]
Try something like `69182.5 > 0`. So, set `value: 0`  and `type: ">"`. Let me know if that works out for you. 

If that is not an option for you then I will need to make Kairos fall back to string comparison as part of this error's error handling. It might get confusing though since `"623" > "5463.5"` returns `true` when doing string comparison.

**Comment by jlee462** [comment]
That did not work, but these two worked:
`69182.5 > 0.0000` and `69182.5 != 0.0000`

It was trying to cast a float to an int so changing the 0 to a float worked. Thank you!!!!

**Comment by timelyart** [comment]
Ah, yes. Thank you for getting back with your findings.
