### ISSUE TITLE
Re Kairos Screener to Watchlist

### ISSUE THREAD

**Issue by joowen** [timelyart/Kairos#5]
Hi Timelyart, I've been watching your videos lately and trying to use the kairos software.

Upon putting in the final command for the watchlist (python main.py screener_to_watchlist), I received an error (please see attachments).

Any help in resolving this would be greatly appreciated!

Thank you.
<img width="1280" alt="Screen Shot 2020-04-18 at 4 52 44 AM" src="https://user-images.githubusercontent.com/43221151/79632963-8e0f4480-8130-11ea-9874-e0ab548221cf.png">
<img width="1280" alt="Screen Shot 2020-04-18 at 4 52 27 AM" src="https://user-images.githubusercontent.com/43221151/79632965-90719e80-8130-11ea-8f23-400150757f29.png">

**Comment by timelyart** [comment]
Fixed in https://github.com/timelyart/Kairos/releases/tag/v2.16

**Comment by joowen** [comment]
Do I have to reinstall anything? Or do I just close everything and reopen?

**Comment by timelyart** [comment]
You can do `git pull` from your **kairos directory** or replace the contents of said directory with the content of the v2.16 zip file. Always, do a `python setup.py install` after upgrading (again from your kairos directory).

**Comment by joowen** [comment]
Is there somewhere I can contact you? I'm just running into another issue and not sure if its something I'm doing wrong. Do you have discord?

**Comment by timelyart** [comment]
I highly encourage the use of issues here, so that others might see solutions to the same problem. That being said, send me an email and we'll take it from there.
