### ISSUE TITLE
Option to specify the webhook URL when creating an Alert

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#51]
Is is possible to specify `Alert actions > Webhook URL`? I've looked through the docs but couldn't find this option.

**Comment by marcfon** [comment]
After digging into the code it turned out to be pretty easy. Just have to specify `charts > alerts > name > webhook: https://test.com`. Might be something for the docs or example yaml files.

**Comment by timelyart** [comment]
The majority of the code base (and documentation) was made 24 to 30 months ago when webhooks where not a feature yet. I should update the documentation for sure, or at the very least put a disclaimer somewhere that not all options are documented. I usually do update YAML files with new features.
