### ISSUE TITLE
Last alert (sometimes) not being set

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#54]
Sometimes the last alert (in alphabetical order) which is process by Kairos isn't set in TradingView.

The log does show that the pair has been process via `process_symbol` but it's not in the alerts list on TV.

**Comment by timelyart** [comment]
This may be an issue where Kairos closes the connection before the alert is set. This should be easily fixable.

**Comment by timelyart** [comment]
It should be fixed with release [release v2.76](https://github.com/timelyart/Kairos/releases/tag/v2.76). but it is hard for me to verify since I could not reproduce it myself.
