### ISSUE TITLE
Backtest breaks on checkbox

### ISSUE THREAD

**Issue by marcfon** [timelyart/Kairos#55]
It seems that backtesting in v2.74 is breaking on a checkbox. See the log below.

```
2022-01-15 10:59:14.101 ERROR tv - get_dialog_input_title: Message: 
Traceback (most recent call last):
  File "/kairos274/tv/tv.py", line 3482, in get_dialog_input_title
    checkbox_label = find_element(element, 'span[class^="label"] > span[class^="label"]')
  File "/tv/tv.py", line 451, in find_element
    element = WebDriverWait(browser, delay).until(
  File "/usr/local/lib/python3.8/site-packages/selenium-3.141.0-py3.8.egg/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by marcfon** [comment]
@timelyart I've tested this on v2.75 and also get the same error. Any chance you can take a look?

**Comment by timelyart** [comment]
So, I did a first test and I don't get any errors. Can you tell me which browser and driver version you use, and share a link to the chart?

**Comment by marcfon** [comment]
> So, I did a first test and I don't get any errors. Can you tell me which browser and driver version you use, and share a link to the chart?

Could you update the QFL ProSum indicator on your chart to the latest version (2.5.20)? The backtest works with earlier versions but something changed in the more recent versions that breaks.

**Comment by marcfon** [comment]
@timelyart The moment it breaks is while reading the default input values. Do you still need a link to a chart or have you been able to reproduce it on your end as well?

**Comment by marcfon** [comment]
The problem is/was cause by the fact the a checkbox didn't have a label. Right now Kairos requires a label in order identify the row in the input dialoge. Not sure if there is a clean way to identify rows that don't have a label but it would be nice if Kairos throws a warning when it encounters such a situation and continues processing. The simple fix in this case was by changing the strategy and adding a label.
