### ISSUE TITLE
Alerts not setting when running on mac if using clipboard

### ISSUE THREAD

**Issue by ridesforlife** [timelyart/Kairos#6]
**Describe the bug**
While running Kairos on a macOS when the program is attempting to fill the alert expiry date and time while using clipboard :true it hangs and alert is never set. It then moves on to next symbol and repeats this process without actually setting the alert

**To Reproduce**
1.  Kairos.cfg, leave clipboard true    
#Using the clipboard will improve the performance significantly but does make use of your clipboard.
clipboard = true

2. In yaml file under expiration ensure open ended is no and choose any time expiration in this eg 5 min
 expiration:
      time: 5
      # Note that open-ended is for premium users only and - when set - will ignore the value for 'time'
      open-ended: no
3. in yaml  run in foreground to see where the alert entry hangs
  run-in-background: no

4, open Kairos folder in terminal window and run python3 main. py. alert_davo.yaml ( or whatever you named this yaml file
 

**Expected behavior**
Opens chrome, goes to trading view. Logs into TV clears old alerts , new tab opens and goes to correct watchlist.  Watchlist symbols collected. Open first chart. Opens alert to set. chooses Davo . When it goes  to enter the expiration date and time it does so but hangs there. You can see red exclamation marks in both the boxes related to expiration date and time.  It will then move onto next symbol and the process repeats without actually setting the alert. If you watch the alert tab nothing every is populated. 

Note if you change clipboard to false it will be able to set the expiration date and time with no difficulty and alert is set normal
Note: if you use open ended alert setting no issue with setting alerts

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome. Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by joowen** [comment]
It's possible to use this on Mac? I've been using it on a virtual machine on my Mac.

**Comment by ridesforlife** [comment]
> It's possible to use this on Mac? I've been using it on a virtual machine on my Mac.

Yes it is possible. Few hiccups with setting alert expiration time as I have mentioned above if using clipboard but other runs fine if you put clipboard to FALSE. Just takes a lot of time to run that way.  If you use open ended with clipboard true has no problems although you run into your alert maximum that way.

**Comment by timelyart** [comment]
This should be fixed with https://github.com/timelyart/Kairos/releases/tag/v2.17. Please, let me know if it did.
