### ISSUE TITLE
New TV layout breaks backtest

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#62]
TradingView introduced a new layout that breaks the backtest. I'm going over the CSS selectors to see what needs to be updated.

**Comment by timelyart** [comment]
Ah. Thank you for letting me know. I am currently on the road and I don't expect to have the peace and quiet until next week to do some actual coding/testing.

**Comment by timelyart** [comment]
Fixed with release [release v2.76](https://github.com/timelyart/Kairos/releases/tag/v2.76).
