### ISSUE TITLE
Invalid XPath error on setting alerts

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#64]
Not sure what happened but suddenly I'm getting this error while setting alerts.

`SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[matches(text(),'(loading|compiling)','i')]' is not a valid XPath expression.`

It happens inside `wait_until_chart_is_loaded()`. Tested with both Chrome 103 and 102 on a M1.

**update**
Also tested on a headless linux machine with driver version 103.0.5060.53 and there it works just fine.

**Comment by timelyart** [comment]
M1?

**Comment by timelyart** [comment]
I cannot reproduce this on Windows either although I am running Chrome 104 Beta since Chrome 103 has a known issue with Selenium.

**Comment by mrcrdwd** [comment]
Haven't seen this error in a while so closing this one.
