### ISSUE TITLE
Add support for setting different timeframes when backtesting strategies

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#67]
The `timeframes` setting in the yaml config is currently ignored when only `strategies` are defined. 

The current implementation only works when `alerts` or `signals` are defined in the yaml.

**Comment by timelyart** [comment]
The best way to backtest is to use a multiple chart layout. The symbol is set to be the same across charts (setting) but with a different timeframe. This way of backtesting has a higher performance than to set each timeframe separately.

It would be easy enough to support but I am not convinced. 
Users would use the `timeframes` setting thinking this is the only/optimal way to do it.

What is your opinion?

**Comment by timelyart** [comment]
I have gone ahead and implemented it and updated the comment section for `timeframes` for the [_strategy.yaml](https://github.com/timelyart/Kairos/blob/master/yaml/_strategies.yaml) file.

**I cannot stress this enough though, if you want to backtest different timeframes use a multi chart layout whereby each chart has the same ticker but is on its own timeframe.**

Added in [release v2.77](https://github.com/timelyart/Kairos/releases/tag/v2.77).
