### ISSUE TITLE
Include HTML in summary email

### ISSUE THREAD

**Issue by alexpunct** [timelyart/Kairos#7]
It would be nice if I could include some custom HTML or at least text in the summary email at the top.

**Comment by timelyart** [comment]
A default html/text for all summaries can be done fairly easy. However, if you want to change the text per summary depending on some condition than that is going to be rather difficult.

What exactly do you want to achieve here?

**Comment by timelyart** [comment]
Aggregated feature requests regarding the summary mail in issue #11 Summary config file

**Comment by alexpunct** [comment]
Maybe pass the .yaml file when generating the summary after you ran it with `python main.py file.yaml -s` and use the description in that yaml file and prepend that to the symmary text

**Comment by timelyart** [comment]
> Maybe pass the .yaml file when generating the summary after you ran it with `python main.py file.yaml -s` and use the description in that yaml file and prepend that to the symmary text

Good thinking. However, I want to be able to summarize the signals separately from the generating them. So, unless the filename is part of the alert message I cannot do that. That being said, it is one possible solution. 

The thing is, the alert message is already getting pretty cluttered and I don't know if there is (or might be) a maximum number of characters. In short, I want to keep the dependency on TradingView as small as possible whilst giving maximum flexibility.

**Comment by alexpunct** [comment]
but this doesn't even need to be in the alerts, when you build the body of the email, you just put some text before it

**Comment by timelyart** [comment]
I suppose I could do something like `-s my.yaml` but the thing is, I'd like to be able to run multiple .yaml after one each other, e.g. daily and weekly on Monday early in the morning. Furthermore, each yaml file can include multiple alerts with each could have their own description. 

Would you like to prepend the email with yaml configured data (e.g. the name of the alert)?
