### ISSUE TITLE
tv - <module>: File  does not exist error

### ISSUE THREAD

**Issue by joowen** [timelyart/Kairos#7]
<img width="1280" alt="Screen Shot 2020-04-18 at 6 25 36 PM" src="https://user-images.githubusercontent.com/43221151/79672670-445f4200-81a2-11ea-83b2-98e55c507baf.png">

**Comment by timelyart** [comment]
Did you rename **_kairos.cfg** to **kairos.cfg** and made the necessary changes to the listed settings?

**Comment by timelyart** [comment]
My guess is that you didn't set `path` under `[webdriver]` to whatever the path is to your webdriver.

**Comment by joowen** [comment]
I renamed the kairos.cfg file. Not sure what you mean by settings, but I applied everything in the notepad++ file.
<img width="1280" alt="Screen Shot 2020-04-18 at 6 37 24 PM" src="https://user-images.githubusercontent.com/43221151/79672873-abc9c180-81a3-11ea-94b5-b6a468ef2d03.png">

**Comment by joowen** [comment]
No I did not do the path thing, what is that? Is that a setting I have to apply a second time?

**Comment by timelyart** [comment]
You have to set the `path` to wherever you have your webdriver downloaded and extracted, e.g. **C:\webdrivers\chromedriver.exe**

**Comment by joowen** [comment]
What should i type into the directory exactly?

**Comment by joowen** [comment]
I put the chrome driver in C:/

**Comment by timelyart** [comment]
Assuming you are using Chrome or Brave, you'll need to download the [Chrome webdriver](https://chromedriver.chromium.org/downloads) corresponding with your version of Chrome/Brave. Extract the webdriver to a location, set `[webdriver] -> path` to full path to that file.

**Comment by timelyart** [comment]
> 
> 
> I put the chrome driver in C:/

your path would be **C:\chromedriver.exe** then

**Comment by joowen** [comment]
So how exactly and where do I set the path?

**Comment by timelyart** [comment]
Open your **kairos.cfg** and set `path` under `[webdriver]` to the aforementioned path.

**Comment by joowen** [comment]
Ok now its logging into tradingview and goes to the right page and selects the screener I have saved, but after that it stops. Like its not adding tickers nor is it scrolling down the page.

**Comment by timelyart** [comment]
I opened a separate issue for that. Please, go to issue #8.
