### ISSUE TITLE
More info about study errors

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#75]
Is there a way to capture more info about why a study error occurs?

In TV you can hover over the ❗️ and see the error message usually. How about doing that and making a screenshot or reading that message from the DOM?

The code does already contain the `is_study_error` function but somehow I feel that it's not always firing. I'm sometimes missing some exported trades CSV files but don't see any errors in the log. In the past, this was due to a study error and now I'm making an assumption that this is also the case.

**Comment by mrcrdwd** [comment]
I need to dig deeper into what's going on here. Let's close this for now.

**Comment by timelyart** [comment]
What exactly is the problem? Does the study randomly stop working? Or does it work for one asset/timeframe and not the other?
