### ISSUE TITLE
Always getting "A new device is using your account"

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#77]
Somehow TV detects every new run of Kairos as a new device (and sends an alert email).

The setting `share_user_data` is set to true and `user_data_directory` is configured correctly.

Also, multiple simultaneous instances of Kairos appear as multiple sessions in the TV sessions overview.

What could be going on?

**Comment by mrcrdwd** [comment]
Could this be related to the default profile in Chrome?

**Comment by timelyart** [comment]
Well, if your 'base profile' is recognized as being from a new device, then this could be possible. This can happen when cookies are reset, for example.

Try cleaning the browser data with the flag `-cls`, i.e. `main.py -cls`. Wait for Kairos to exit and then try to run Kairos as you would normally.

**Comment by mrcrdwd** [comment]
What if you're running on a headless server and you haven't logged in to TV before. I don't think any cookies have been set yet in this case. You're basically working with the base profile chrome comes with.

**Comment by timelyart** [comment]
Yes, that would do it. I don't think a dynamic ip address (e.g. VPN) is a problem - it never has been for me at least.

I will need to investigate and see if I can login on the base profile prior to copying it for each instance.

**Comment by mrcrdwd** [comment]
I agree and don't think it's an ip adress issue. I think the base chrome profile is the "guest" one.

**Comment by timelyart** [comment]
I found one bug which specifically happens on first time use (when your browser user profile is copied): the cookie banner on the landing page only shows up after scrolling down. As no cookie banner is found Kairos assumes it has been accepted previously. 
I updated the code so that Kairos first scrolls down and then tries to find the cookie banner. 

Can you run Kairos with `-cls` and run multiple instances thereafter? Does this fix the issue?

**Comment by mrcrdwd** [comment]
Great catch! Initial testing looks good. Have spawned 5 instances, and they register as a single session on TV. So what's the next limitation here? Are hardware resources the only thing limiting how many simultaneous sessions we can run?

**Comment by mrcrdwd** [comment]
Curious if this will still work when you span instances for different TV user accounts. Maybe the username needs to be part of the folder that's copied at startup?

**Comment by timelyart** [comment]
> Great catch! Initial testing looks good. Have spawned 5 instances, and they register as a single session on TV. So what's the next limitation here? Are hardware resources the only thing limiting how many simultaneous sessions we can run?

That is great to hear. Hardware resources and bandwidth are really the only limitations, yes.

**Comment by timelyart** [comment]
> Curious if this will still work when you span instances for different TV user accounts. Maybe the username needs to be part of the folder that's copied at startup?

Technically, that should be possible. However, I won't support it as this would facilitate a way to circumvent TV's limitations on their tiered user model. Kairos is made to automate tasks you can do already with your account (i.e. acting in good faith) and not to circumvent their business model.

**Comment by timelyart** [comment]
Case closed. Huzzah!
