### ISSUE TITLE
Selects the screener I have saved, but after that it stops

### ISSUE THREAD

**Issue by timelyart** [timelyart/Kairos#8]
**Describe the bug**
Selects the screener I have saved, but after that it stops. Like its not adding tickers nor is it scrolling down the page.

It seems to be bugged for large lists. For some reason, TV now goes to the end of the list and so you have to scroll up to see all markets whereas previously it was the other way around.

**Comment by timelyart** [comment]
Which type of screener are you using? I just ran a crypto screener which seemed to work fine. 
Please open the log file that corresponds with your YAML and share any errors that Kairos encountered. You can find the log files by default under **Kairos\log**.

**Comment by joowen** [comment]
I am attaching a screenshot here.
<img width="1280" alt="Screen Shot 2020-04-18 at 7 29 16 PM" src="https://user-images.githubusercontent.com/43221151/79673809-f7cc3480-81aa-11ea-885e-31ded1c7fdab.png">

**Comment by joowen** [comment]
I am running a stock screener.

**Comment by timelyart** [comment]
Well, I tested it. It seems to be bugged for large lists. For some reason, TV now goes to the end of the list and so you have to scroll up to see all markets whereas previously it was the other way around.

**Comment by timelyart** [comment]
TradingView doesn't show all rows unless you scroll to the very end. Programmatic scrolling no longer has an effect. Since Kairos couldn't find all symbols, it will try again ad infinitum. I've found a workaround by first sorting the table. Testing it now.

**Comment by timelyart** [comment]
While stress testing, I discovered that TV has a limit of a 1000 symbols per watchlist. I'm including a workaround for that as well as part of patching this bug.

**Comment by timelyart** [comment]
Fixed in https://github.com/timelyart/Kairos/releases/tag/v2.17

**Comment by joowen** [comment]
Works like magic! Thank you!!
