### ISSUE TITLE
Signals taking significantly longer to generate

### ISSUE THREAD

**Issue by debonair99** [timelyart/Kairos#80]
've been using Kairos version 2.54 for a long time without upgrading to newer versions as it had been working amazingly for me until recently.  Attempted to upgrade and use v2.79 and signals are taking exponentially longer to generate (previously ~1-2s and now 12-14s). Watched it run and with the newer version each ticker seems to be typed by Kairos manually rather than simply scrolling through the watchlist?
![Clipboard - September 27, 2022 7_02 PM](https://user-images.githubusercontent.com/85971842/195853607-22c87a79-24ee-45ea-899a-d4cbd14b424c.png)

Any ideas how to optimise performance back to 1-2s for signals to be generated?
Cheers

**Comment by timelyart** [comment]
Just to be sure... are you generating signals or creating alerts?

10-12 seconds for signals is really a lot. With the current version I have between 2.5 and 4 seconds per market which is still significantly higher than your previous performance. I'll have a look into it but don't get your hopes up yet.

**Comment by debonair99** [comment]
Defintely generating signals. Have been using v2.54 for nearly 10 months to generate signals and it was working flawlessly. Took max 50 minutes to go through 2 watchlists that each had 1000 tickers in them. 
Only recently v2.54 had an issue where the watchlist generated wouldn't import automatically (screenshot attached) so I decided to test v2.79 and noticed the signals where taking an extraordinary amount of time to generate. Assuming its more pragmatic to look into why 2.79 signals are taking so long to generate rather than looking at 2.54's inability to import the watchlist as it is the newer version? Cheers
![Untitled](https://user-images.githubusercontent.com/85971842/195976059-541f0ec8-8b9c-4f51-b2c5-6272afeea483.png)

**Comment by timelyart** [comment]
The markup of the website  changed recently which is why the watchlist isn't automatically saved. I have already updated the code just need to make a release. 

It may well be that not all signals were triggered properly, i.e. the chart wasn't fully loaded. So, there may have been signals even though Kairos told you there weren't. 

Can you test for me whether v2.54 and v2.79 give the same amount of signals?

**Comment by debonair99** [comment]
I tested both and both versions generated the same amount of signals.
Please see attached. 2.79 took 6x as long to complete and neither was able to import the watchlist successfully.
If there is a way to fix the import watchlist function in v2.54 that would be ideal as the v2.79 takes an unworkable amount of time to process the signals!
![image](https://user-images.githubusercontent.com/85971842/196008124-1324a01f-34f8-4bbf-93e7-826276bfc9b9.png)
![image](https://user-images.githubusercontent.com/85971842/196008141-2cb18e79-8e42-4890-a8f5-eadc3078d605.png)

**Comment by timelyart** [comment]
The import watchlist is fixed in [version 2.80](https://github.com/timelyart/Kairos/releases/tag/v2.80).

I can't update v2.54 but I will investigate the differences between that version and v2.79+.

**Comment by timelyart** [comment]
I have found the issue. The part of the website that Kairos uses in v279+ to check whether a market is still valid has changed. 
Working on a fix now.

**Comment by timelyart** [comment]
Fixed in [version 2.81](https://github.com/timelyart/Kairos/releases/tag/v2.81).
