### ISSUE TITLE
Coloured console log (nice to have)

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#81]
Would you consider adding some color to the console output? It can improve readability. There are different libraries like [coloredlogs](https://coloredlogs.readthedocs.io/en/latest/) (my preference) and [colorlog](https://pypi.org/project/colorlog/) which make it quite easy to implement. The coloring can also be added to `kairos.cfg`.

**Comment by timelyart** [comment]
What kind of coloring do you want? 

Something like:
- `INFO` lines in white
- `WARNING` lines  in yellow
- `ERROR` lines in red

Anything else? Do you want to be able to highlight specific keywords?

**Comment by mrcrdwd** [comment]
I'd say just use the default highlighting initially and use `kairos.cfg` to specify the [environment variables](https://coloredlogs.readthedocs.io/en/latest/api.html#id18) so that everyone can customize the style to their liking?

Or when you decide to go without an external library go for the colors you suggest.

**Comment by timelyart** [comment]
For now, I don't care enough about console colour. So, I went with your preferred option. It also seems the easiest to set up. 

I won't make a separate release for it but it is pushed to the master branche. Don't forget to install the library (or run `install setup.py`) if you are running in a virtual environment.
