### ISSUE TITLE
Something broke xpath

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#89]
Just the other day, when creating new TV alerts, I ran into this weird issue. It's coming from `wait_until_chart_is_loaded()`.

```
Message: invalid selector: Unable to locate an element with the xpath expression //*[matches(text(),'(loading|compiling)','i')] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[matches(text(),'(loading|compiling)','i')]' is not a valid XPath expression.
  (Session info: chrome=108.0.5359.98)
```

Maybe something changed on the Chromedriver? I tried to debug this one but it's hard to actually catch the chart loading moment.

I don't have this issue on a headless linux machine which is also running the 108 chromedriver version. Just on macos (didn't test windows).

**Comment by mrcrdwd** [comment]
Could this be related? 

"Selenium supports XPath 1.0 version while fn:matches is from XPath 2.0." [source](https://stackoverflow.com/questions/53354813/xpath-using-matches-and-regex-working-in-xpath-tester-but-in-code-throwing-inval?rq=1)

The strange thing is that as far as I know this used to work fine but I'll admit that I usually set my alerts via the linux box.

**Comment by timelyart** [comment]
I am not disregarding it yet but it has worked up until now. Which version of Chrome and ChromeDriver are you using?

I haven't been able to reproduce the problem with version 108.0.5359.x

**Comment by mrcrdwd** [comment]
Yeah this is a strange one. I'm on browser version: 108.0.5359.98 and driver version: 108.0.5359.71.

**Comment by timelyart** [comment]
Well.... I can't reproduce the issue. The method seems to work on my end. 

Is the chart/study/indicator information visible in the top left of the chart?
Do you run it in a multi chart layout?

edit: I use the same browser and driver version.

**Comment by mrcrdwd** [comment]
Did you try it when creating alerts? On a backtest I don't get into `wait_until_chart_is_loaded()`. After some more testing, the problem seems to be related to `matches()` somehow.

**Comment by mrcrdwd** [comment]
Using `"//*[contains(text(),'loading') or contains(text(),'compiling')]"` seems to fix the issue. From everything I read it seems that `matches()` isn't supported by Selenium... So why didn't it break sooner? And why does it work on other platforms?

**Comment by mrcrdwd** [comment]
@timelyart I see that you merged it into the main branch. Not sure if it's going to be a problem in the future but `contains()` is of course less strict than `match()`. Any thoughts on why this error has become apparent now and not earlier? And why you don't seem to be affected.

**Comment by timelyart** [comment]
Well... it isn't so much about Selenium as it which version of xpath the browser uses. `matches()` is `xpath 2.0` whilst `contains` is `xpath 1.0`. I could have gotten support for xpath 2.0 via a 3rd party library (e.g. a browser plugin).
I probably chose to use `matches()` because I thought I needed regex. 

I implemented your solution `//*[contains(text(),'loading') or contains(text(),'compiling')]` solution.
