### ISSUE TITLE
Summary subject line configurable in tv/yaml files

### ISSUE THREAD

**Issue by alexpunct** [timelyart/Kairos#9]
I would like to have the subject line of the summary email be configurable so I can distinguish between different Kairos runs. 
The reason is because I am running 1 configuration weekly, another configuration daily and I would like to be able to distinguish between the summary emails.

**Comment by timelyart** [comment]
That is not really how the summary was meant to be used. The summary mail should contain all alerts that have not been summarized before. It's very clean.

I suppose what I could do is to make the subject a command line option. Would that work for you?

**Comment by timelyart** [comment]
Aggregated feature requests regarding the summary mail  in issue #11 Summary config file
