### ISSUE TITLE
New alerts dialog support

### ISSUE THREAD

**Issue by mrcrdwd** [timelyart/Kairos#90]
TV completely changed the layout of the alerts dialog. This breaks the existing code.

**Comment by mrcrdwd** [comment]
@timelyart need any help with this?

**Comment by timelyart** [comment]
Already working on it. 

I updated the css but I need to make a fail mechanism for stale elements and do some stress tests.

**Comment by timelyart** [comment]
Fixed in [release v2.86](https://github.com/timelyart/Kairos/releases/tag/v2.86).
