### ISSUE TITLE
Incomplete loading of TV strategies

### ISSUE THREAD

**Issue by timelyart** [timelyart/Kairos#92]
**Description**
Strategies that are linked to a second indicator do not load properly. This is a known bug and TV is aware of it. See [this comment](https://github.com/timelyart/Kairos/commit/ad887700c0798bdf9cfc82485b48927fa38e0334#commitcomment-93450114).

**Solution**
Add a YAML option that is used to execute code to specifically handle issues with Kairos that are of a direct consequence of this bug in TV.

**Comment by timelyart** [comment]
Fixed as of [release v2.87](https://github.com/timelyart/Kairos/releases/tag/v2.87).

**Comment by mrcrdwd** [comment]
> **Description** Strategies that are linked to a second indicator do not load properly. This is a known bug and TV is aware of it. See [this comment](https://github.com/timelyart/Kairos/commit/ad887700c0798bdf9cfc82485b48927fa38e0334#commitcomment-93450114).

For the record, I wouldn't describe this as the strategy not loading properly. They load just fine. The problem is that the TV layout doesn't behave as expected.
