### ISSUE TITLE
Login Issues and Alert Creation

### ISSUE THREAD

**Issue by oimista** [timelyart/Kairos#97]
Hi,

Pretty new to this so if I'm doing something wrong then I apologise.

Couple of issues I have:

1. If I leave the login details blank and enter them when asked in the console I get a successful login, but if I enter the login details in the kairos.cfg file it errors out every time.
2. I get the following error when trying to create alerts: 

ERROR tv - create_alert: Message:
Traceback (most recent call last):
  File "C:\Kairos-2.87\tv\tv.py", line 2375, in create_alert
    wait_and_click(alert_dialog, css_1st_row_left, 30)
  File "C:\Kairos-2.87\tv\tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-3.141.0-py3.9.egg\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

![signinerror](https://user-images.githubusercontent.com/123581127/214691358-6b9fe77a-aa6d-4faa-8424-85e7f816fe2b.png)
![20230125_121133](https://user-images.githubusercontent.com/123581127/214691554-a75c295a-8e89-4515-a471-39fa310b9e7d.png)

Thanks.

**Comment by timelyart** [comment]
I have tested the login procedure from _**kairos.cfg**_ and found no bugs. That is, it is working as expected. I don't think the login procedure and the failure to create alerts is related unless you have a slow internet connection. 

So, I need some more information. Please provide the following:

- operating system
- chrome version
- chrome driver version
- your _**kairos.cfg**_ without the sensitive data

**Comment by oimista** [comment]
Thanks for the reply, I'm sure it will be something at my end, just new to running your app.

Don't think I have changed anything in the cfg file other than put the chrome driver info in there.

OS = Win10
browser version: 109.0.5414.120
driver version: 109.0.5414.74

[kairos-upload.txt](https://github.com/timelyart/Kairos/files/10510128/kairos-upload.txt)

Thanks.

**Comment by timelyart** [comment]
Can you set `share_user_data = true` in your _**kairos.cfg**_ and see if that makes a difference?

Don't worry your data does not leave your computer. It merely will share your browser's user data between sessions and enables you to continue to use Chrome next to Kairos.

I assume you have high bandwidth, but can you tell me how high your bandwidth is?

**Comment by oimista** [comment]
Bandwidth is 50/15 Mbps should be enough?

Still the same error unfortunately

Traceback (most recent call last):
  File "C:\Kairos-2.87\tv\tv.py", line 2375, in create_alert
    wait_and_click(alert_dialog, css_1st_row_left, 30)
  File "C:\Kairos-2.87\tv\tv.py", line 436, in wait_and_click
    return WebDriverWait(browser, delay).until(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium-3.141.0-py3.9.egg\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by timelyart** [comment]
Ah. I see what happened. There were several fixes to the Alert dialog the past month but they weren't rolled into a release yet. 
Please, install the [latest release](https://github.com/timelyart/Kairos/releases/tag/v2.88), v2.88. 

This should fix it.

**Comment by oimista** [comment]
That looks to be working there now, thank you very much for the quick response and fix.

The only thing I'm having trouble with now is the webhook URL being added, I have it in the yml file under the webhooks section but it doesn't get added to the alert.  Is there somewhere else I should have that defined?

**Comment by timelyart** [comment]
You probably used `webhooks` under `summary`. Which is part of an elaborate workaround to send alerts to webhooks when you couldn't set it directly in the alert dialogue. 

I noticed that I never updated the example files with the webhook option. They have been [updated](https://github.com/timelyart/Kairos/tree/master/yaml) and will be included in the next release.

Please, add `webhook: <your webhook link>` to your YAML as per the following snippet:
```
    # Communication options
    send:
      ...
    # Send to a webhook. Optional. Leave the value empty or remove the line if you don't want to define a webhook.
    webhook: https://test
    message:
      prepend: no
      ...
```

**Comment by oimista** [comment]
Amazing, webhook is working, but adding text into the alert message doesn't appear to be working.

I really appreciate all this help and work you are doing, are you still in control of the addresses on your donation page?

Thanks.

**Comment by timelyart** [comment]
You are right. It seems the text gets deleted right after it is added. I'll fix it and make a new release.

> I really appreciate all this help and work you are doing, are you still in control of the addresses on your donation page?

Thank you for the kind words. A donation is much appreciated but please use [one of the new addresses](https://github.com/timelyart/Kairos/blob/master/DONATE.md). I decided to update the donation addresses as BTC and ETH were both legacy addresses, and Dash is all but a distant memory. 

Happy to know Kairos is helpful for you. 👍

**Comment by timelyart** [comment]
> Amazing, webhook is working, but adding text into the alert message doesn't appear to be working.

The alert message textbox should be fixed in [v3.1](https://github.com/timelyart/Kairos/releases/tag/v3.1).

**Comment by oimista** [comment]
That's all working now, thank you so much for the changes.

Is there anyway I can add the bar closing price in to the alerts text?

**Comment by timelyart** [comment]
> That's all working now, thank you so much for the changes.

Great! I'll close the issue then.

> Is there anyway I can add the bar closing price in to the alerts text?
Currently, no.

Please [open a feature request](https://github.com/timelyart/Kairos/issues/new?assignees=&labels=&template=feature_request.md) and I'll get to it when I have time.
