### ISSUE TITLE
Message Box

### ISSUE THREAD

**Issue by oimista** [timelyart/Kairos#98]
Additions to the message Text box

Price info
JSON to allow alerts sent to discord

**Comment by timelyart** [comment]
Thank you for opening a feature request. 

I'll add the following price info:
- open
- close
- high
- low

Concerning JSON, aren't you able to set the message box with JSON already? Or, am I misunderstanding what you want to achieve?

Bear in mind that extracting the price info might infringe on TV's (future) Terms of Use, Policies and Disclaimers.
For example, extracting the closing price of an alert for personal use might be fine, but sharing it with discord may not. If you distribute TV data commercially (e.g. a paid discord channel) it most definitely is not allowed.

**Comment by oimista** [comment]
If I add anything in the format from this example - https://www.tradingview.com/chart/US30/8KxfMSLI-How-To-Send-Alerts-From-TradingView-To-Discord/ - I get an error:

ERROR tools - get_yaml_config: while parsing a block mapping
  in "yaml\test.yaml", line 62, column 7
expected <block end>, but found '<scalar>'
  in "yaml\test.yaml", line 73, column 18

ERROR tv - run: argument of type 'NoneType' is not iterable

Thanks.

**Comment by timelyart** [comment]
You might want to try to put the JSON in between apostrophes `'` or, alternatively, escape special characters like `[, ], {, } " and '`.

The following example should work:
`text: '{"content": "Buy 1 min {{exchange}}:{{ticker}}, price = {{close}} Time ={{time}}"}'`

**Comment by timelyart** [comment]
So, I didn't think this through. OHLC data at alert creation is quite irrelevant. 
You want to use the OHLC data when the alert gets triggered. To this end you can use `{{open}}`, `{{high}}`, `{{low}}` and `{{close}}'`.

For example:
`"%NAME %TIMEFRAME: %SYMBOL \nOHLC: {{open}}, {{high}}, {{low}}, {{close}}\n%CHART"`

That is what you want, right?

**Comment by oimista** [comment]
I shall test and let you know.

Thanks.

**Comment by timelyart** [comment]
Since I haven't heard back, I am going to assume you came to the same conclusion as mine. Namely, that you want to use TV's own `{{open}}`, `{{high}}`, `{{low}}` and `{{close}}`. 

Closing the issue.
